sudo: false
language: node_js
node_js:
  - 14
script:
  - yarn eslint 'src/**'
  - yarn test:coveralls
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
