version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./volumes/data:/data/db
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
